steps:
    - id: 'install-terragrunt'
      waitFor: ['-']
      name: 'hashicorp/terraform:1.4.4'
      dir: './infra'
      entrypoint: 'sh'
      args:
          - '-c'
          - |
              echo "Installing Terragrunt"
              wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.46.2/terragrunt_linux_amd64
              chmod u+x terragrunt
              mv terragrunt /usr/local/bin/terragrunt
    - id: 'tg-plan'
      waitFor: ['install-terragrunt']
      name: 'hashicorp/terraform:1.4.4'
      dir: './infra'
      entrypoint: 'sh'
      args:
          - '-c'
          - |
              echo "Planning..."
              terragrunt init
              terragrunt plan
    - id: 'tg-apply'
      waitFor: ['tg-plan']
      name: 'hashicorp/terraform:1.4.4'
      dir: './infra'
      entrypoint: 'sh'
      args:
          - '-c'
          - |
              echo "Applying.."
              terragrunt init
              terragrunt apply -auto-approve
