steps:
    - id: 'tg-plan'
      waitFor: ['-']
      name: 'hashicorp/terraform:1.4.6'
      dir: './infra'
      entrypoint: 'sh'
      args:
          - '-c'
          - |
              echo "Installing Terragrunt"
              wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.46.2/terragrunt_linux_amd64
              chmod u+x terragrunt
              mv terragrunt /usr/local/bin/terragrunt
              echo "Initing..."
              terragrunt init
              echo "Planning..."
              terragrunt plan
              echo "Applying..."
              terragrunt apply -auto-approve
